version: "3.8"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
    # Do "id" in your terminal to find your ids
      - PUID=<UID>
      - PGID=<GID>
      - TZ=Asia/Singapore # Feel free to change this
    volumes:
      - /path/to/your/prowlarr-config:/config
    ports:
      - "<port>:9696" # Consider changing this avoid conflicting ports
    networks:
      - <docker-network>
    restart: unless-stopped

networks:
  <docker-network>:
    external: true
