version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./vw-data:/data
    environment:
      - ADMIN_TOKEN=supersecrettokenhere
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://passwords.kawaii-san.org
