version: '3'

services:
  whoogle-search:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    restart: unless-stopped
    ports:
      - "9008:5000"
    environment:
      WHOOGLE_CONFIG_COUNTRY: "SG" # Or your country code
      WHOOGLE_CONFIG_LANGUAGE: "lang_en" 
