version: "3"
services:
  vaultwarden:
    image: whoogle:latest
    container_name: whoogle
    restart: unless-stopped
    ports:
      - "90008:80"
    volumes:
      - ./vw-data:/data
    environment:
      - ADMIN_TOKEN=supersecrettokenhere
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://passwords.kawaii-san.org
