version: "3.9"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "9006:80"
    volumes:
      - /home/kawaiisan:/srv
      - ./config:/config
      - ./database:/database
    environment:
      - PUID=1000
      - PGID=1000
