version: "3.8"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "9005:4533"  # Host port 9005 -> Container's 4533
    environment:
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
    volumes:
      - ./data:/data      # Navidrome config & DB
      - ~/Music:/music  # Replace with your actual music folder path
